# Generated by Django 4.2.3 on 2024-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='brain_injury_details',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise, desk job)'), ('lightly_active', 'Lightly Active (light exercise/sports 1-3 days/wk)'), ('moderately_active', 'Moderately Active (moderate exercise/sports 6-7 days/wk)'), ('very_active', 'Very Active (hard exercise every day, or 2x/day)'), ('extra_active', 'Extra Active (hard exercise 2+ hrs/day, training for marathon, triathlon, etc.)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='initial_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='determination_level',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('determined', 'Determined'), ('very_determined', 'Very Determined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('bulk', 'Bulk'), ('lose_weight', 'Lose weight'), ('healthy_happiness', 'Healthy happiness'), ('improve_posture', 'Improve posture'), ('stress_reduction', 'Stress reduction'), ('improve_flexibility', 'Improve flexibility'), ('improve_endurance', 'Improve endurance'), ('six_pack', 'Six Pack')], max_length=20, null=True),
        ),
    ]
