# Generated by Django 4.2.3 on 2024-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_brain_injury_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brain_injury_severity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brain_injury_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
