# Generated by Django 4.2.3 on 2024-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_brain_injury_type_userprofile_brain_injury_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='general_context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
