# Generated by Django 4.2.3 on 2024-03-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('medication', 'Medications/important stuff'), ('commitments', 'Commitments/Strategies/Proactive Planning/Obligations/Responsibilities'), ('routines', 'Breaking-and-building Routines/Habits'), ('self_care', 'Self-care/Well-being'), ('productivity', 'Productivity/Time Management'), ('learning', 'Learning/Skill Development'), ('relationships', 'Relationships/Social Connections'), ('fitness', 'Fitness/Health'), ('financial', 'Financial Management'), ('personal_interests', 'Personal Interests/Entertainment'), ('other', 'Other')], default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='reminder',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
