# Generated by Django 4.2.3 on 2024-03-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', max_length=10)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.reminder')),
            ],
        ),
    ]
