# Generated by Django 4.2.3 on 2024-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='seconds', max_length=10),
        ),
    ]
